baseurl = "https://julio-ort.github.io/"
languageCode = "en-us"
title = "Julio Ortega"
theme = "hugo-theme-casper"
paginate = 2
Copyright = "© Julio Ortega 2020"
canonifyurls = true

[params]
description = "ASU Computer Science"
authorlocation = "authorlocation"
cover = "images/cover.png"
## save the image you want to use as background picture in directory "./static/images"author = "author name"(delete this line when editing)
logo = "images/logo.png"
## save the image you want to use as website logo in directory "./static/images"(delete this line when editing)


githubName = "julio-ort"
linkedinName = "your linkedin name"
email = "julio.ortega54@gmail.com"
instagramName = "julio.ort"
hideHUGOSupport = false


[[menu.main]]  # here are the buttons on the menu
name = "Home" # Button will display as "Home"
weight = 100 # the weight decides the position of the button (higher or lower)
identifier = "home"
pre = "<br />"
url = "/"

[[menu.main]]
name = "Contact"
weight = 0
identifier = "contact" # this button will refer to a markdown file named "contact" in the content folder
pre = "<br />"
url = "/contact"

[[menu.main]]
name = "Blog"
identifier = "blog" # this page will refer to a markdown file named "blog" in the content folder
pre = "<br />"
url = "/post"
weight = 40

[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
